platform :ios, '9.0'

target 'MRPro' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MRPro
  pod 'SwiftyJSON'

  target 'MRProTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MRProUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
